jobs:
  check:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Start Up
        uses: actions/checkout@v2
      - name: Install Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./main/ci

name: Verify

on:
  schedule:
    - cron: "20 */6 * * *"
